name: flutter_ui_elements
description: "📱 UI Elements Demo - Flutter Version. Una aplicación educativa que demuestra diferentes elementos de interfaz de usuario de Flutter."

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Habilitar assets si necesitamos imágenes
  # assets:
  #   - images/

  # Fonts personalizadas si las necesitamos
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf